# This is a basic workflow to help you get started with Actions

name: CI_bar

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  call-workflow-in-another-repo:
    uses: MundraAnkur/foo/.github/workflows/blank.yml@main
    with:
      username: Ankur
  run-make:
    runs-on: ubuntu-latest
    steps:
    - run: |
        make start-minikube
        minikube ip
      working-directory: ${{ github.action_path }}/../../..
      shell: bash
