name: Test Windup Addon

on:
  workflow_dispatch:
  
jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run End-to-End Test
        run: make test-e2e
